### ISSUE TITLE
Failed reachability test

### ISSUE THREAD

**Issue by mcnesium** [Nitrokey/nextbox#36]
Though everything seems to work as expected, the Nextbox App shows reachability test failure in the HTTPS / TLS  section:

<img src="https://user-images.githubusercontent.com/476060/137117869-e12a2e3c-29f2-4034-9248-c4e565310225.png" width="50%" height="auto"/>

This is behind a regular Fritzbox with all settings applied exactly like described [in the docs](https://docs.nitrokey.com/nextbox/remote/index.html).

NextBox Daemon Version: 1.0.11-1
NextBox App Version: 1.0.5
Nextcloud 21.0.0

**Comment by daringer** [comment]
this should be fixed with the DNS-based certificate verification, feel free to re-open if still valid

**Comment by mcnesium** [comment]
This is still an issue. 

![image](https://github.com/user-attachments/assets/678f6f6f-924e-404e-a073-5de71b4a6b47)

Full domain `cloud.***.de` is set in the exclusion list of the Fritzbox DNS-Rebind Protection .
